# Generated by Django 3.2.5 on 2021-07-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_comments',
            field=models.ManyToManyField(related_name='favorited_comment', to='api.Comment'),
        ),
    ]
