# Generated by Django 3.2.5 on 2021-07-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commentlike_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to='post_pics'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_pic',
            field=models.ImageField(default='default.png', upload_to='user_pics'),
        ),
    ]
