# Generated by Django 3.2.5 on 2021-07-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_favorite_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
